# Method: Inferring quadratic interactions

In [1]:
import numpy as np
import sys
import matplotlib.pyplot as plt
import simulate_quadratic as smlqd
#import inference
%matplotlib inline

from scipy import linalg

np.random.seed(1)

In [2]:
# parameter setting:
n = 4    # number of variables
g = 0.5    # coupling variance

w0 = np.random.normal(0.0,g/np.sqrt(n),size=(n,n))

In [3]:
q0 = smlqd.generate_interaction(g,n)

l = 100
s = smlqd.generate_data(w0,q0,l)

In [4]:
print(s[:10,:])

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1. -1. -1. -1.]
 [ 1.  1. -1.  1.]
 [ 1. -1. -1. -1.]
 [ 1.  1.  1.  1.]
 [ 1.  1. -1.  1.]
 [-1. -1.  1.  1.]
 [-1. -1. -1.  1.]
 [-1.  1. -1.  1.]]


In [5]:
m = np.mean(s,axis=0)
ds = s - m
st1 = s[1:]

c = np.cov(ds,rowvar=False,bias=True)
c1 = linalg.inv(c) # inverse
dst = ds[:-1].T
H = st1
W = np.empty((n,n)) #; H0 = np.empty(n)
Q = np.empty((n,n,n))

In [6]:
i0 = 0
h = H[:,i0]
q = Q[i0,:,:]

In [7]:
h_av = h.mean()

# q[i,j,k] = sum_i1i2 <dh_i*ds_i1*ds_i2> * [C_inv]_ji1 * [C_inv]_ki2
# - sum_l <dh_i * ds_l> sum_i1,i2,i3 * <ds_i1 * ds_i2 * s_i3>*[C_inv]_ji1 * [C_inv]_ki2 * [C_inv]_li3
# 

In [8]:
print(h)

[ 1.  1.  1.  1.  1.  1. -1. -1. -1. -1.  1.  1.  1.  1. -1. -1.  1.  1.
  1.  1. -1.  1.  1. -1. -1. -1. -1.  1.  1. -1. -1. -1. -1. -1. -1. -1.
  1.  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1.
  1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1. -1. -1. -1.  1. -1. -1. -1.
 -1. -1. -1.  1.  1.  1.  1. -1.  1.  1.  1. -1. -1. -1. -1. -1. -1. -1.
  1. -1. -1. -1.  1.  1.  1. -1. -1.]


In [9]:
print(h_av)

-0.1919191919191919


In [10]:
dh = h - h_av
print(dh)

[ 1.19191919  1.19191919  1.19191919  1.19191919  1.19191919  1.19191919
 -0.80808081 -0.80808081 -0.80808081 -0.80808081  1.19191919  1.19191919
  1.19191919  1.19191919 -0.80808081 -0.80808081  1.19191919  1.19191919
  1.19191919  1.19191919 -0.80808081  1.19191919  1.19191919 -0.80808081
 -0.80808081 -0.80808081 -0.80808081  1.19191919  1.19191919 -0.80808081
 -0.80808081 -0.80808081 -0.80808081 -0.80808081 -0.80808081 -0.80808081
  1.19191919  1.19191919  1.19191919  1.19191919  1.19191919 -0.80808081
 -0.80808081 -0.80808081 -0.80808081 -0.80808081 -0.80808081 -0.80808081
 -0.80808081 -0.80808081 -0.80808081 -0.80808081 -0.80808081  1.19191919
  1.19191919  1.19191919  1.19191919  1.19191919 -0.80808081 -0.80808081
 -0.80808081 -0.80808081 -0.80808081 -0.80808081 -0.80808081 -0.80808081
 -0.80808081 -0.80808081  1.19191919 -0.80808081 -0.80808081 -0.80808081
 -0.80808081 -0.80808081 -0.80808081  1.19191919  1.19191919  1.19191919
  1.19191919 -0.80808081  1.19191919  1.19191919  1

In [11]:
ds = ds[:-1]

# dhdsds[i1,i2] = mean_t dh[t]*ds[t,i1]*ds[t,i2]
dhds = dh[:,np.newaxis]*ds
dhdsds = np.dot(dhds.T,ds)/(l-1)

In [12]:
# q1[j,k] = sum_i1i2 dhdsds[i1,i2]*C_inv[j,i1]*C_inv[k,i2] 
q1 = np.dot(c_inv,dhdsds)
q1 = np.dot(q1,c_inv.T)

In [13]:
print(q1.shape)

(4, 4)


In [14]:
# ss[t,i,j] = s[t,i]*s[t,j]
a = np.array([[1,2],[3,4]])
b = np.array([[0.1,0.2],[0.3,0.4]])
print(a)


[[1 2]
 [3 4]]


In [15]:
print(b)

[[0.1 0.2]
 [0.3 0.4]]


In [16]:
c = a*b
print(c)

[[0.1 0.4]
 [0.9 1.6]]
